// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCejn2iJkqs8cCKSsq85D6LbNUb2m90VQQ',
    appId: '1:440860067666:web:51a28d5630e310c470dc8b',
    messagingSenderId: '440860067666',
    projectId: 'hmapp-af281',
    authDomain: 'hmapp-af281.firebaseapp.com',
    storageBucket: 'hmapp-af281.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUk8pGU8CHz8LQIGgsWSAyElB1thmL6wE',
    appId: '1:440860067666:android:01f4e45245274e1670dc8b',
    messagingSenderId: '440860067666',
    projectId: 'hmapp-af281',
    storageBucket: 'hmapp-af281.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUTLPz6O9esLQbkwkZVKrGFvVEyJDwAJ4',
    appId: '1:440860067666:ios:d5ca72b3bca44f2c70dc8b',
    messagingSenderId: '440860067666',
    projectId: 'hmapp-af281',
    storageBucket: 'hmapp-af281.appspot.com',
    iosClientId: '440860067666-v643hmrq0ia93u7udvramnrhnm16ih6q.apps.googleusercontent.com',
    iosBundleId: 'com.example.hmapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUTLPz6O9esLQbkwkZVKrGFvVEyJDwAJ4',
    appId: '1:440860067666:ios:d5ca72b3bca44f2c70dc8b',
    messagingSenderId: '440860067666',
    projectId: 'hmapp-af281',
    storageBucket: 'hmapp-af281.appspot.com',
    iosClientId: '440860067666-v643hmrq0ia93u7udvramnrhnm16ih6q.apps.googleusercontent.com',
    iosBundleId: 'com.example.hmapp',
  );
}
